# basic options
title: Alan Cromlish
author: Alan Cromlish
email: your-email@domain.com
description: A wonderful site
instagram_username: 01alan20
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
